### ISSUE TITLE
Hamburger menu icon

### ISSUE THREAD

**Issue by pinglinh** [pinglinh/pinglinh.com#2]
The hamburger icon is not clickable when in mobile format.
When I'm using dev tools, I can't actually click on the menu icon element as it's covered by the wrapper element. I have tried to include a z-index but this does not work on both the wrapper and the menu icon.
![screen shot 2016-11-20 at 15 20 30](https://cloud.githubusercontent.com/assets/16864061/20463924/6b2f8036-af35-11e6-9a6a-eae71c375c41.png)

**Comment by taw** [comment]
That is totally impossible 😏
<img width="1231" alt="screen shot 2016-12-03 at 17 40 15" src="https://cloud.githubusercontent.com/assets/17444/20861193/85f81c38-b981-11e6-9ebf-663f6ee32888.png">

**Comment by pinglinh** [comment]
@taw OMG!! Thanksss!!!!!!!!!!!!!!!!!
